### ISSUE TITLE
Supporting units

### ISSUE THREAD

**Issue by juliohm** [subnero1/MapMaths.jl#1]
Hi @ettersi , thanks for this package, it has a really great design.

As I shared on Discourse, we are starting to generalize the coordinate system infrastructure in [Meshes.jl](https://github.com/JuliaGeometry/Meshes.jl) (submodule of the [GeoStats.jl](https://github.com/JuliaEarth/GeoStats.jl) framework) and would like to reuse existing work whenever possible.

One thing that I think could be improved in the current implementation is the support for Unitful.jl or DynamicQuantities.jl units. It would be nice to be able to type `LatLon(0°, 30°)` and `NorthEast(0m, 100km)` for example.

Do you have plans to incorporate units in this package? How can we join efforts to generalize these coordinates a bit further and reuse in Meshes.jl? Do you plan to maintain this package in the long-term? Have you considered the possibility of leaving your current company and losing write access to the repository?

**Comment by ettersi** [comment]
Hi @juliohm, thanks for the kind words!

> One thing that I think could be improved in the current implementation is the support for Unitful.jl or DynamicQuantities.jl units. It would be nice to be able to type `LatLon(0°, 30°)` and `NorthEast(0m, 100km)` for example.
>
> Do you have plans to incorporate units in this package?

I had no plans to work on the interoperability between MapMaths and Unitful / DynamicQuantities so far, but I'm happy to discuss. I suspect the way this would work is that MapMaths would come in a "plain numbers" flavour (the current API) and a unitful flavour. The entry point to the unitful flavour would be to enter your coordinates as unitful quantities (e.g. `LatLon(1.3°, 103.8°)`), and then when you do coordinate conversions MapMaths would return the result in some default units (e.g. `EastNorth(LatLon(1.3°, 103.8°)) -> EastNorth(1.2e7m, 1.4e5m)` where `m` is the default unit for `EastNorth` coordinates). One issue with this design is that we would need a way to distinguish the unitful / unitless versions of `WebMercator`, and there currently isn't a natural way for doing so. 

> Do you plan to maintain this package in the long-term? Have you considered the possibility of leaving your current company and losing write access to the repository?

MapMaths is quite fundamental to the work we do at Subnero; therefore, I intend to maintain this package as part of my day job for the foreseeable future, and I have both economic support and incentives for doing so. Should anything change about this plan, then both Subnero and I will happily hand over this packages to whoever else is keen to maintain it.

Having said that, I should possibly also mention that I don't expect there to be a lot of maintenance work. MapMaths has only two dependencies (StaticArrays and Elliptic), and I don't expect either of these packages to undergo major changes all that often. And MapMaths itself has a fairly simple design philosophy and narrow scope, so while there may be the occasional bug fix / feature request for some edge cases, I don't expect there to be major rewrites of large sections of this library.

**Comment by juliohm** [comment]
Thank you @ettersi , we are brainstorming some design ideas and will come back with a more concrete plan soon. We see the issue of units as something of major importance, and also the ability to navigate the different coordinate types with sensible defaults. Good to hear that you will be maintaining the package in the long-term.

**Comment by juliohm** [comment]
@ettersi do you have good references for the Elliptic integrals used in EastNorth <> LatLon conversions?

**Comment by ettersi** [comment]
Sorry for the late reply, it's been a busy couple of days. 

The formula for the `Lat -> North` conversion was taken from https://en.wikipedia.org/wiki/Meridian_arc#Calculation.

**Comment by juliohm** [comment]
Thank you @ettersi for the reference. Given that we are progressing well with unitful coordinates in our stack, I will close this issue.

**Comment by ettersi** [comment]
Just out of curiosity, what was the resolution? MapMaths explicitly stops you from passing in units, so are you stripping the units before handing over to MapMaths, or are you not using MapMaths at all?

**Comment by juliohm** [comment]
We are not using MapMaths.jl. Instead we are working on an alternative design that is units-aware from the beginning. In that sense it never constructs WebMercator with coordinates in km for example. It respects the EPSG specification.

Meshes.jl is the place where this work is happening. We are happy to incorporate ideas there if you want to depend on it in the future.
